state-alchemists/zrb

- .github/workflows/_zrb.yml
- docs/concepts/task-env-file.md
- docs/concepts/task-env.md
- docs/concepts/task-group.md
- docs/concepts/task/notifier.md
- docs/getting-started.md
- pyproject.toml
- src/zrb/__init__.py
- zrb_init.py
> Release 0.3.0

- pyproject.toml
Update pyproject.toml
See: https://github.com/state-alchemists/zrb/pull/72
> edit pyproject.toml

- .github/workflows/_zrb.yml
- pyproject.toml
- src/zrb/task/base_task/component/base_task_model.py
Make sure `To run this again` is only shown if the task has CLI interface
> Release 0.4.1

- docs/getting-started.md
- docs/plugins.md
> WIP: improve docs

- docs/concepts/task/flow-task.md
- install.sh
- pyproject.toml
- src/zrb/builtin/devtool/aws/install.sh
- src/zrb/builtin/devtool/devtool_install.py
- src/zrb/builtin/devtool/gvm/download.sh
- src/zrb/builtin/devtool/gvm/resource/config.sh
- src/zrb/builtin/devtool/helix/install.sh
- src/zrb/builtin/devtool/kubectl/install.sh
- src/zrb/builtin/devtool/nvm/resource/config.sh
- src/zrb/builtin/devtool/pyenv/download.sh
- src/zrb/builtin/devtool/pyenv/resource/config.sh
- src/zrb/builtin/devtool/selenium/install.sh
- src/zrb/builtin/devtool/zsh/install.sh
- src/zrb/builtin/git.py
- src/zrb/task/flow_task.py
> update to version 0.5.0

- docs/concepts/copying-task.md
- docs/concepts/extending-cmd-task.md
- docs/concepts/extending-task.md
- docs/concepts/runner-group-and-task.md
- docs/concepts/specialized-tasks/rsync-task.md
- docs/concepts/template-rendering.md
- docs/getting-started.md
- pyproject.toml
- src/zrb/task/any_task.py
- src/zrb/task/base_task/base_task.py
> Improve docs

- pyproject.toml
> update to version 0.6.1

- docs/maintainer-guide.md
> Fix documentation

- pyproject.toml
- src/zrb/builtin/generator/pip_package/add.py
> Fix generated package version

- .gitignore
> remove poetry lock

- docs/installation.md
- install.sh
> remove build flags

- project.sh
> update build flag

- project.sh
- src/zrb/builtin/generator/plugin/template/project.sh
- src/zrb/builtin/generator/project/template/project.sh
> update poetry version in project.sh

- install.sh
> add termux-api

- install.sh
> update installed packages

- src/zrb/builtin/generator/project/template/project.sh
> consider termux support for generated project

- docs/installation.md
> add wakelock instruction

- install.sh
> add swig on termux

- src/zrb/builtin/generator/fastapp/template/src/kebab-zrb-app-name/docker-compose.yml
> Add missing docker profile

- src/zrb/__main__.py
- src/zrb/action/runner.py
- src/zrb/helper/cli.py
- src/zrb/helper/default_env.py
- src/zrb/helper/file/copy_tree.py
- src/zrb/helper/loader/load_module.py
> remove low impact logging condition

- src/zrb/helper/cli.py
- src/zrb/helper/loader/load_module.py
> refactor CLI

- install.sh
> fix installation script

- src/zrb/builtin/generator/fastapp/add.py
- src/zrb/builtin/generator/fastapp/template/src/kebab-zrb-app-name/src/config.py
- src/zrb/builtin/generator/fastapp/template/src/kebab-zrb-app-name/src/integration/app.py
- src/zrb/builtin/generator/fastapp/template/src/kebab-zrb-app-name/src/module/auth/entity/group/api.py
- src/zrb/builtin/generator/fastapp/template/src/kebab-zrb-app-name/src/module/auth/entity/permission/api.py
- src/zrb/builtin/generator/fastapp/template/src/kebab-zrb-app-name/src/module/auth/entity/user/api.py
- src/zrb/builtin/generator/fastapp/template/src/kebab-zrb-app-name/src/module/log/entity/activity/api.py
- src/zrb/builtin/generator/fastapp/template/src/kebab-zrb-app-name/src/module/log/entity/activity/event.py
- src/zrb/builtin/generator/fastapp/template/src/kebab-zrb-app-name/src/start.sh
- src/zrb/builtin/generator/fastapp_crud/template/src/kebab-zrb-app-name/src/module/snake_zrb_module_name/entity/snake_zrb_entity_name/api.py
> implement tracing

- src/zrb/builtin/generator/pip_package/template/_automate/snake_zrb_package_name/cmd/publish.sh
- src/zrb/builtin/generator/pip_package/template/_automate/snake_zrb_package_name/local.py
- src/zrb/builtin/generator/plugin/template/_cmd/publish.sh
- src/zrb/builtin/generator/plugin/template/zrb_init.py
> update publish pip command

- docs/configurations.md
- install.sh
- src/zrb/__init__.py
- src/zrb/config/config.py
- src/zrb/shell-scripts/ensure-podman-is-installed.sh
- src/zrb/task/docker_compose_task.py
- src/zrb/task/wiki_task.py
Add podman backend, add wiki tasks
> Release/v 0.10.0

- pyproject.toml
> increase version

- .github/workflows/hello.yml
- src/zrb/builtin/project/create/template/.github/workflows/hello.yml
- zrb_init.py
The plugin should be imported first before the entire playground
> Fix import order for playground testing

- pyproject.toml
> Release/v 0.11.1

- docs/concepts/README.md
- docs/concepts/runner-group-and-task.md
- docs/concepts/specialized-tasks/README.md
- docs/concepts/specialized-tasks/server.md
- docs/faq/does-zrb-have-a-scheduler.md
- docs/getting-started.md
- docs/technical-documentation/tasks/server.md
- src/zrb/__init__.py
- src/zrb/builtin/process/pid/get_by_name.py
- src/zrb/builtin/schedule.py
- src/zrb/builtin/watch_changes.py
- src/zrb/task/base_task/base_task.py
- src/zrb/task/recurring_task.py
- src/zrb/task/server.py
- zrb_init.py
Deprecate `RecurringTask`, introduce `ServerTask`
> Introduce server

- docs/technical-documentation/tasks/path-watcher.md
- docs/technical-documentation/tasks/time-watcher.md
- pyproject.toml
- src/zrb/__init__.py
- src/zrb/action/runner.py
- src/zrb/builtin/_helper/reccuring_action.py
- src/zrb/builtin/schedule.py
- src/zrb/builtin/watch_changes.py
- src/zrb/helper/callable.py
- src/zrb/task/any_task.py
- src/zrb/task/base_task/base_task.py
- src/zrb/task/checker.py
- src/zrb/task/cmd_task.py
- src/zrb/task/http_checker.py
- src/zrb/task/looper.py
- src/zrb/task/path_checker.py
- src/zrb/task/path_watcher.py
- src/zrb/task/port_checker.py
- src/zrb/task/resource_maker.py
- src/zrb/task/server.py
- src/zrb/task/time_watcher.py
- src/zrb/task/watcher.py
- test/task/path_watcher/test_path_watcher.py
Introduce watcher with looper, minimizing inter-trigger blind spot while using Server
> introduce watcher

- docs/configurations.md
- pyproject.toml
- src/zrb/config/config.py
- src/zrb/helper/cli.py
- src/zrb/helper/loader/load_module.py
- src/zrb/helper/loader/load_script.py
Introducing ZRB_INIT_MODULES config
```
export ZRB_INIT_MODULES=zrb_noto
zrb
```
> introduce ZRB_INIT_MODULES

- .github/workflows/_zrb.yml
- .github/workflows/hello.yml
- .github/workflows/release.yml
- poetry.lock
- pyproject.toml
- src/zrb/builtin/project/add/fastapp_template/requirements.txt
> Version 1.0.0

- .github/workflows/_zrb.yml
> Update github workflow

- docs/changelog.md
- poetry.lock
- pyproject.toml
- src/zrb/__main__.py
- src/zrb/builtin/project/add/fastapp/fastapp_template/my_app_name/requirements.txt
- src/zrb/builtin/project/add/fastapp/fastapp_template/my_app_name/test/test_homepage.py
- src/zrb/task/llm_task.py
- zrb_init.py
> Update dependencies, fix fastapp test
> Update dependencies + fix fastapp test

- src/zrb/builtin/project/add/fastapp/fastapp_template/my_app_name/README.md
> Update fastapp docs

- poetry.lock
- pyproject.toml
- src/zrb/task/base_task.py
- src/zrb/task/llm_task.py
> Introduce MCP Server

- src/zrb/builtin/llm/tool/file.py
- src/zrb/task/llm_task.py
> Update json tool

- docs/changelog.md
- src/zrb/__main__.py
- src/zrb/builtin/llm/tool/api.py
- src/zrb/builtin/llm/tool/cli.py
- src/zrb/builtin/llm/tool/file.py
- src/zrb/builtin/llm/tool/rag.py
- src/zrb/builtin/llm/tool/web.py
- src/zrb/builtin/project/add/fastapp/fastapp_template/my_app_name/common/error.py
- src/zrb/task/llm_task.py
- src/zrb/util/file.py
> Expand user on file path

- test/builtin/llm/test_history.py
- test/builtin/llm/test_input.py
- test/builtin/test_base64.py
- test/builtin/test_git.py
- test/builtin/test_git_subtree.py
- test/builtin/test_md5.py
- test/test_main.py
> Increase test coverage

- docs/changelog.md
- src/zrb/builtin/__init__.py
- src/zrb/builtin/llm/chat_session.py
- src/zrb/builtin/llm/llm_ask.py
- src/zrb/builtin/llm/llm_chat.py
- src/zrb/callback/any_callback.py
- src/zrb/callback/callback.py
- src/zrb/input/text_input.py
- src/zrb/runner/web_route/home_page/home_page_route.py
- src/zrb/runner/web_route/node_page/group/show_group_page.py
- src/zrb/runner/web_route/node_page/group/view.html
- src/zrb/runner/web_route/node_page/task/show_task_page.py
- src/zrb/runner/web_route/node_page/task/view.html
- src/zrb/runner/web_route/task_session_api_route.py
- src/zrb/task/base_task.py
- src/zrb/task/base_trigger.py
- src/zrb/task/llm/agent.py
- src/zrb/task/llm/print_node.py
- src/zrb/task/llm_task.py
- test/builtin/llm/test_input.py
Breaking changes: use llm-ask instead of llm-chat for single query, add various new configuration and make them lazy-loaded.
> WIP: Make chat continuous

- docs/changelog.md
- pyproject.toml
- src/zrb/task/llm/history.py
- test/builtin/llm/test_history.py
Update ConversationHistory to not use pydantic
> More lazy load

- .github/workflows/_zrb.yml
- docs/changelog.md
- pyproject.toml
- src/zrb/config/default_prompt/file_extractor_system_prompt.md
- src/zrb/config/default_prompt/interactive_system_prompt.md
- src/zrb/config/default_prompt/persona.md
- src/zrb/config/default_prompt/repo_summarizer_system_prompt.md
- src/zrb/config/default_prompt/summarization_prompt.md
- src/zrb/config/default_prompt/system_prompt.md
- src/zrb/runner/cli.py
- Refine persona to be more general
- Enhance repo summarizer with examples and clearer instructions
- Standardize system and interactive prompts for consistency
> Improve default prompts

- docs/changelog.md
- pyproject.toml
- src/zrb/builtin/llm/chat_session.py
- src/zrb/builtin/llm/llm_ask.py
- src/zrb/builtin/llm/tool/sub_agent.py
- src/zrb/config/llm_config.py
- src/zrb/task/any_task.py
- src/zrb/task/base/context.py
- src/zrb/task/base_task.py
- src/zrb/task/llm/agent.py
- src/zrb/task/llm/config.py
- src/zrb/task/llm/tool_wrapper.py
- src/zrb/task/llm_task.py
- src/zrb/util/attr.py
- test/config/test_llm_config.py
- Add to_function method on BaseTask
- LLMTask's yolo_mode might contain tool names.
> WIP: Fix BaseTask to_fn
